### ISSUE TITLE
Errors at first run

### ISSUE THREAD

**Issue by Favna** [M4cs/EGTR-FutureRestore#5]
After setting up all the requirements with `pip` I ran the program and pressed `continue` to download FutureRestore but then I got this thrown into my Powershell:

```
PS E:\UserFiles\Downloads\EGTR-FutureRestore> python .\egtr.py
Traceback (most recent call last):
  File ".\egtr.py", line 12, in <module>
    screens.futureRestoreQuestion()
  File "E:\UserFiles\Downloads\EGTR-FutureRestore\screens.py", line 22, in futureRestoreQuestion
    downloadFutureRestore()
  File "E:\UserFiles\Downloads\EGTR-FutureRestore\utilities.py", line 34, in downloadFutureRestore
    zip_ref = zipfile.ZipFile(DOWNLOAD_DIRECTORY + "/futurerestore.zip", 'r')
  File "C:\Program Files (x86)\Python\Python3\lib\zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "C:\Program Files (x86)\Python\Python3\lib\zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Preceeding pip result:
```
PS E:\UserFiles\Downloads\EGTR-FutureRestore> pip3 install -r .\requirements.txt
Collecting PySide2 (from -r .\requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e8/55/2ca8d420d1df22ce6bb4b8e94819f40e383ca54ccaf74caa993cbb176fe1/PySide2-5.12.1-5.12.1_1-cp35.cp36.cp37-none-win32.whl
Collecting PyQt5 (from -r .\requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/49/1d/6eabcd8bb11598818c2cc98caae37af6ab48067c92bd7893fa48c676f1c5/PyQt5-5.12-5.12.1_a-cp35.cp36.cp37.cp38-none-win32.whl
Collecting requests (from -r .\requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting shiboken2==5.12.1 (from PySide2->-r .\requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/fa/f2/45d366a9aa6edd416fe6822c5a748d9a2239ce3b726c61bfe734963431a5/shiboken2-5.12.1-5.12.1-cp35.cp36.cp37-none-win32.whl
Collecting PyQt5_sip<4.20,>=4.19.14 (from PyQt5->-r .\requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/32/73/ef5dc9cc37c132b705afd58aaf4ef7db8036849a53cb35ce45d864d96117/PyQt5_sip-4.19.14-cp37-none-win32.whl
Collecting certifi>=2017.4.17 (from requests->-r .\requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->-r .\requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r .\requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->-r .\requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Installing collected packages: shiboken2, PySide2, PyQt5-sip, PyQt5, certifi, idna, chardet, urllib3, requests
Successfully installed PyQt5-5.12 PyQt5-sip-4.19.14 PySide2-5.12.1 certifi-2018.11.29 chardet-3.0.4 idna-2.8 requests-2.21.0 shiboken2-5.12.1 urllib3-1.24.1
```

**Comment by Favna** [comment]
Update: Ubuntu doesn't fair much better

```
➜  EGTR-FutureRestore git:(master) pip3 install -r requirements.txt
Collecting PySide2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/67/16/e312e5d60f677ba69aabd30bac9e20e2136797c1a9d4e26fcd6524ba672b/PySide2-5.12.1-5.12.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (144.0MB)
    100% |████████████████████████████████| 144.0MB 7.7kB/s
Collecting PyQt5 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/01/8c/eeff014306fcdbb8afda0fe603d1b458dddf2be0ca10d561b0015e439357/PyQt5-5.12-5.12.1_a-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (61.1MB)
    100% |████████████████████████████████| 61.1MB 18kB/s
Collecting requests (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 3.9MB/s
Collecting shiboken2 (from PySide2->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/4e/a7/efa256fed7a07a8a679cbce755cab37cdb85744f990351bd2a9bd8ba796b/shiboken2-5.12.1-5.12.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (178kB)
    100% |████████████████████████████████| 184kB 3.1MB/s
Collecting PyQt5_sip<4.20,>=4.19.14 (from PyQt5->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/94/b5/ee9e2f594e11e762c1a04529549b4a3264037861c01b073fbc992676066b/PyQt5_sip-4.19.14-cp36-cp36m-manylinux1_x86_64.whl (67kB)
    100% |████████████████████████████████| 71kB 5.0MB/s
Collecting urllib3<1.25,>=1.21.1 (from requests->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 3.9MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.0MB/s
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 3.3MB/s
Collecting idna<2.9,>=2.5 (from requests->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 5.6MB/s
Installing collected packages: shiboken2, PySide2, PyQt5-sip, PyQt5, urllib3, chardet, certifi, idna, requests
Successfully installed PyQt5-5.12 PyQt5-sip-4.19.14 PySide2-5.12.1 certifi-2018.11.29 chardet-3.0.4 idna-2.8 requests-2.21.0 shiboken2-5.12.1 urllib3-1.24.1
➜  EGTR-FutureRestore git:(master) python3 egtr.py

(python3:10846): Gtk-WARNING **: 23:58:48.096: Theme parsing error: gtk.css:559:1: Expected a valid selector

(python3:10846): Gtk-WARNING **: 23:58:48.097: Theme parsing error: gtk.css:1148:2: Expected semicolon

(python3:10846): Gtk-WARNING **: 23:58:48.098: Theme parsing error: gtk.css:1489:27: Expected a valid selector

(python3:10846): Gtk-WARNING **: 23:58:48.098: Theme parsing error: gtk.css:1618:15: 'bborder-color' is not a valid property name

(python3:10846): Gtk-WARNING **: 23:58:48.098: Theme parsing error: gtk.css:1622:20: Expected a valid selector

(python3:10846): Gtk-WARNING **: 23:58:48.099: Theme parsing error: gtk.css:1988:15: 'bborder-color' is not a valid property name

(python3:10846): Gtk-WARNING **: 23:58:48.104: Theme parsing error: gtk.css:4363:2: Expected semicolon

(python3:10846): Gtk-WARNING **: 23:58:48.106: Theme parsing error: gtk.css:4994:2: Junk at end of value for border-radius

(python3:10846): Gtk-WARNING **: 23:58:48.109: Theme parsing error: gtk.css:6305:26: Expected a valid selector

(python3:10846): Gtk-WARNING **: 23:58:48.111: Theme parsing error: gtk.css:7321:26: Expected a valid selector

(python3:10846): Gtk-WARNING **: 23:58:48.113: Theme parsing error: gtk.css:8201:64: Junk at end of value for background-image

(python3:10846): Gtk-WARNING **: 23:58:48.114: Theme parsing error: gtk.css:8820:55: Using one color stop with linear-gradient() is deprecated.

(python3:10846): Gtk-WARNING **: 23:58:48.115: Theme parsing error: gtk.css:8820:55: Missing closing bracket at end of linear gradient

(python3:10846): Gtk-WARNING **: 23:58:48.115: Theme parsing error: gtk.css:8933:19: not a number

(python3:10846): Gtk-WARNING **: 23:58:48.115: Theme parsing error: gtk.css:8951:15: 'bcbcbc' is not a valid color name

(python3:10846): Gtk-WARNING **: 23:58:48.118: Theme parsing error: gtk.css:10394:20: Not a valid image
Traceback (most recent call last):
  File "egtr.py", line 12, in <module>
    screens.futureRestoreQuestion()
  File "/home/favna/Downloads/EGTR-FutureRestore/screens.py", line 22, in futureRestoreQuestion
    downloadFutureRestore()
  File "/home/favna/Downloads/EGTR-FutureRestore/utilities.py", line 38, in downloadFutureRestore
    os.chmod(DOWNLOAD_DIRECTORY + '/futurerestore', '+x')
TypeError: an integer is required (got type str)
```

**Comment by M4cs** [comment]
ah okay you can fix that by changing '+x' on Line 38 in the download function to 0777
